spring:
    application:
        name: Jisi-Server
    data:
        redis:
            host: localhost
            password: ${ REDIS_PASSWORD }
            port: 6379
    datasource:
        password: ${ PASSWORD }
        url: ${ DB_URL }
        username: ${ USERNAME }
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
    jwt:
        access:
            expiration: 36000
        refresh:
            expiration: 86400
        secret: ${ JWT_KEY }
