spring:
    application:
        name: Jisi-Server
    datasource:
        url: jdbc:mysql://localhost:3306/jisi
        username: root
        password: mingyu08
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
