name: CI/CD using github actions & docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: "main"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: make application.yml
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION }}" > ./application.yml

      - name: set chmod
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKERHUB_ID }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t jisi . # Dockerfile 경로 수정
          docker tag jisi ${{ secrets.DOCKERHUB_ID }}/jisi:latest
          docker push ${{ secrets.DOCKERHUB_ID }}/jisi:latest

      - name: Deploy with SSH
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }} # EC2 인스턴스 퍼블릭 DNS
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }} # pem 키
          port: ${{ secrets.PORT }} # ssh port (22)
          envs: GITHUB_SHA
          script: |
            script: |
            docker login -u ${{ secrets.DOCKERHUB_ID }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker stop jisi
            docker rm jisi
            docker network disconnect redis-network jisi
            docker rmi ${{ secrets.DOCKERHUB_ID }}/jisi:latest
            docker pull ${{ secrets.DOCKERHUB_ID }}/jisi:latest
            docker run -d -p 80:8080 --name jisi ${{ secrets.DOCKERHUB_ID }}/jisi:latest
            docker network connect redis-network jisi

  deploy:

    runs-on: ubuntu-latest
    permissions: write-all
    needs: build

    steps:
      - uses: actions/checkout@v3